### ISSUE TITLE
Whitelisting IP's not working

### ISSUE THREAD

**Issue by Ahmadre** [shyim/shopware-chart#4]
We wanted to whitelist some incoming IP's, but adding the IP of our NGINX Load-Balancer is not working.

<img width="426" alt="Bildschirmfoto 2021-04-19 um 13 21 14" src="https://user-images.githubusercontent.com/18512224/115228556-370cc880-a112-11eb-8b04-2bbc8ec7a64f.png">

It's also the same IP as the domain: myshopware.com

Are we doing anything wrong here?

Should we adjust any annotations for the ingress in this chart?

**Comment by shyim** [comment]
You need to configure symfony trusted proxies https://symfony.com/doc/current/deployment/proxies.html
