### ISSUE TITLE
Production ready chart

### ISSUE THREAD

**Issue by robjuz** [shyim/shopware-chart#5]
Hello @shyim 

First of all, thank you for you work. I use you docker images.

As a Kubernetes fan I come across this repository. Unfortunately it's not production ready. 

So based on this I created my own one. Maybe you could take a look into this?
https://github.com/robjuz/helm-charts/tree/master/charts/shopware

I would also appreciate an advice how to automatically keep tracking changes in other branches and trigger a release of a new version, when a need docker image is ready?

**Comment by shyim** [comment]
Do you maybe want to create a PR?
