### ISSUE TITLE
Disable debug mode

### ISSUE THREAD

**Issue by tomolenet** [shyim/shopware-chart#7]
### Question

Thank you for this chart. It works quite well. Because of  this issue #5 I assume this chart is production ready. Is there any chance to set `debug=false`?
  
![image](https://user-images.githubusercontent.com/38924650/170337245-25228061-c1c3-415f-8e78-011197744d55.png)

Otherwise Symfony may show error messages to clients
  
![image](https://user-images.githubusercontent.com/38924650/170337989-56442cbc-37dc-41c7-ace5-156c6119886f.png)

**Comment by shyim** [comment]
This [needs](https://github.com/FriendsOfShopware/shopware-chart/blob/master/values.yaml#L69) to be false and [this](https://github.com/FriendsOfShopware/shopware-chart/blob/master/values.yaml#L90) prod
